### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by XiaogeWang** [macacajs/XCTestWD#184] opened 2020-12-18 11:36 UTC
Building for iOS, but the linked and embedded framework 'Swifter.framework' was built for iOS + iOS Simulator.
Building for iOS, but the linked and embedded framework 'SwiftyJSON.framework' was built for iOS + iOS Simulator.
Building for iOS, but the linked and embedded framework 'CocoaLumberjackSwift.framework' was built for iOS + iOS Simulator.
Building for iOS, but the embedded framework 'Fuzi.framework' was built for iOS + iOS Simulator.
Building for iOS, but the linked and embedded framework 'CocoaLumberjack.framework' was built for iOS + iOS Simulator.
Building for iOS, but the embedded framework 'AEXML.framework' was built for iOS + iOS Simulator.

mac os 11.0.1 
xcode 12.3

**Comment by ganjarpanji** [comment] 2020-12-18 17:01
duplicated https://github.com/macacajs/XCTestWD/issues/182
please update xctestwd using latest version.

**Comment by paradite** [comment] 2020-12-20 09:28
duplicate of #182 . re-open if error persists

**Closed by paradite** 2020-12-20 09:28 UTC
